"""initial schema

Revision ID: 256645024de6
Revises: 
Create Date: 2026-03-25 14:21:40.980919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '256645024de6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('ghl_connections',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('token_last4', sa.String(length=4), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rrc_county_status',
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('oil_record_count', sa.Integer(), nullable=False),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rrc_data_syncs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('new_records', sa.Integer(), nullable=False),
    sa.Column('updated_records', sa.Integer(), nullable=False),
    sa.Column('unchanged_records', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rrc_gas_proration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=10), nullable=False),
    sa.Column('lease_number', sa.String(length=50), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('lease_name', sa.String(length=255), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('unit_acres', sa.Float(), nullable=True),
    sa.Column('allowable', sa.Float(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rrc_gas_proration_district'), 'rrc_gas_proration', ['district'], unique=False)
    op.create_index(op.f('ix_rrc_gas_proration_lease_number'), 'rrc_gas_proration', ['lease_number'], unique=False)
    op.create_table('rrc_metadata',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('oil_rows', sa.Integer(), nullable=False),
    sa.Column('gas_rows', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_records', sa.Integer(), nullable=False),
    sa.Column('updated_records', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rrc_oil_proration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district', sa.String(length=10), nullable=False),
    sa.Column('lease_number', sa.String(length=50), nullable=False),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('lease_name', sa.String(length=255), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('unit_acres', sa.Float(), nullable=True),
    sa.Column('allowable', sa.Float(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    postgresql_ignore_search_path=True
    )
    op.create_index(op.f('ix_rrc_oil_proration_district'), 'rrc_oil_proration', ['district'], unique=False)
    op.create_index(op.f('ix_rrc_oil_proration_lease_number'), 'rrc_oil_proration', ['lease_number'], unique=False)
    op.create_table('rrc_sync_jobs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oil_rows', sa.Integer(), nullable=False),
    sa.Column('gas_rows', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('photo_url', sa.String(length=512), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=True),
    sa.Column('tool', sa.Enum('EXTRACT', 'TITLE', 'PRORATION', 'REVENUE', name='tooltype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_file_size', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_tool'), 'jobs', ['tool'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('extract_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entry_number', sa.String(length=20), nullable=False),
    sa.Column('primary_name', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('suffix', sa.String(length=20), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('mailing_address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extract_entries_job_id'), 'extract_entries', ['job_id'], unique=False)
    op.create_table('proration_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('owner', sa.String(length=500), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('interest', sa.Float(), nullable=False),
    sa.Column('interest_type', sa.String(length=50), nullable=True),
    sa.Column('appraisal_value', sa.Float(), nullable=True),
    sa.Column('legal_description', sa.String(length=255), nullable=True),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('property_id', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('raw_rrc', sa.String(length=100), nullable=True),
    sa.Column('rrc_lease', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=10), nullable=True),
    sa.Column('lease_number', sa.String(length=50), nullable=True),
    sa.Column('block', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('abstract', sa.String(length=50), nullable=True),
    sa.Column('rrc_acres', sa.Float(), nullable=True),
    sa.Column('est_nra', sa.Float(), nullable=True),
    sa.Column('dollars_per_nra', sa.Float(), nullable=True),
    sa.Column('well_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proration_rows_job_id'), 'proration_rows', ['job_id'], unique=False)
    op.create_table('revenue_statements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=False),
    sa.Column('payor', sa.String(length=255), nullable=True),
    sa.Column('operator_name', sa.String(length=255), nullable=True),
    sa.Column('check_number', sa.String(length=100), nullable=True),
    sa.Column('check_amount', sa.Float(), nullable=True),
    sa.Column('check_date', sa.String(length=20), nullable=True),
    sa.Column('owner_number', sa.String(length=100), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('total_gross', sa.Float(), nullable=True),
    sa.Column('total_tax', sa.Float(), nullable=True),
    sa.Column('total_deductions', sa.Float(), nullable=True),
    sa.Column('total_net', sa.Float(), nullable=True),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_statements_job_id'), 'revenue_statements', ['job_id'], unique=False)
    op.create_table('title_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('legal_description', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('duplicate_flag', sa.Boolean(), nullable=False),
    sa.Column('has_address', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_title_entries_job_id'), 'title_entries', ['job_id'], unique=False)
    op.create_table('revenue_rows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=255), nullable=True),
    sa.Column('property_number', sa.String(length=100), nullable=True),
    sa.Column('sales_date', sa.String(length=20), nullable=True),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('product_description', sa.String(length=100), nullable=True),
    sa.Column('decimal_interest', sa.Float(), nullable=True),
    sa.Column('interest_type', sa.String(length=50), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('property_gross_volume', sa.Float(), nullable=True),
    sa.Column('property_gross_revenue', sa.Float(), nullable=True),
    sa.Column('owner_volume', sa.Float(), nullable=True),
    sa.Column('owner_value', sa.Float(), nullable=True),
    sa.Column('owner_tax_amount', sa.Float(), nullable=True),
    sa.Column('tax_type', sa.String(length=50), nullable=True),
    sa.Column('owner_deduct_amount', sa.Float(), nullable=True),
    sa.Column('deduct_code', sa.String(length=50), nullable=True),
    sa.Column('owner_net_revenue', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['revenue_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_rows_statement_id'), 'revenue_rows', ['statement_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenue_rows_statement_id'), table_name='revenue_rows')
    op.drop_table('revenue_rows')
    op.drop_index(op.f('ix_title_entries_job_id'), table_name='title_entries')
    op.drop_table('title_entries')
    op.drop_index(op.f('ix_revenue_statements_job_id'), table_name='revenue_statements')
    op.drop_table('revenue_statements')
    op.drop_index(op.f('ix_proration_rows_job_id'), table_name='proration_rows')
    op.drop_table('proration_rows')
    op.drop_index(op.f('ix_extract_entries_job_id'), table_name='extract_entries')
    op.drop_table('extract_entries')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_jobs_tool'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('rrc_sync_jobs')
    op.drop_index(op.f('ix_rrc_oil_proration_lease_number'), table_name='rrc_oil_proration')
    op.drop_index(op.f('ix_rrc_oil_proration_district'), table_name='rrc_oil_proration')
    op.drop_table('rrc_oil_proration')
    op.drop_table('rrc_metadata')
    op.drop_index(op.f('ix_rrc_gas_proration_lease_number'), table_name='rrc_gas_proration')
    op.drop_index(op.f('ix_rrc_gas_proration_district'), table_name='rrc_gas_proration')
    op.drop_table('rrc_gas_proration')
    op.drop_table('rrc_data_syncs')
    op.drop_table('rrc_county_status')
    op.drop_table('ghl_connections')
    op.drop_table('app_config')
    # ### end Alembic commands ###
